### ISSUE TITLE
"code":"F00","name":"NotAcceptedError"

### ISSUE THREAD

**Issue by rawadrifai** [interledgerjs/moneyd#101]
I'm trying to run moneyd 
```
moneyd xrp:configure --testnet
XRP secret (master or regular key) (optional):
acquiring testnet account...
got testnet address "rs7pP4hDP9PeDHvzc9XX2us2ekC9xYEtmX"
waiting for testnet API to fund address...
moneyd xrp:start --testnet

```

and it gives me the following error:

```
starting moneyd
2019-05-18T05:00:07.392Z connector:route-broadcaster info generated random routing secret.
2019-05-18T05:00:07.404Z connector:accounts info add account. accountId=parent
2019-05-18T05:00:07.407Z connector:accounts info add account. accountId=local
2019-05-18T05:00:07.418Z connector:admin-api info listen called
2019-05-18T05:00:07.422Z connector:balance-middleware info initializing balance for account. accountId=parent minimumBalance=-Infinity maximumBalance=20000000
2019-05-18T05:00:07.424Z connector:balance-middleware info initializing balance for account. accountId=local minimumBalance=-Infinity maximumBalance=Infinity
2019-05-18T05:00:08.225Z connector:/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-xrp-asym-client/index.js[parent] info creating outgoing channel. from=rs7pP4hDP9PeDHvzc9XX2us2ekC9xYEtmX to=rJEi339p24K7SozLDyfsvrn14J1qLg4Z6A amount=10
2019-05-18T05:00:14.422Z connector:/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-xrp-asym-client/index.js[parent] info transaction complete
2019-05-18T05:00:15.027Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2019-05-18T05:00:00.387Z","data":"sodium.sodium_malloc is not a function","protocolData":[]}
    at Plugin.callback (/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-btp/src/index.ts:666:20)
    at Plugin.listener (/usr/local/share/.config/yarn/global/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit (/usr/local/share/.config/yarn/global/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin._handleIncomingBtpPacket (/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-btp/src/index.ts:711:14)
    at Plugin._handleIncomingWsMessage (/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-btp/src/index.ts:528:18)
    at WebSocketReconnector.EventEmitter.emit (/usr/local/share/.config/yarn/global/node_modules/eventemitter2/lib/eventemitter2.js:354:19)
    at WebSocket._instance.on (/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-btp/src/ws-reconnect.ts:133:70)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/usr/local/share/.config/yarn/global/node_modules/ilp-plugin-btp/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:189:13)```

**Comment by rawadrifai** [comment]
So I try to run this after: https://github.com/interledgerjs/ilp-protocol-stream/blob/master/example.js
And it hangs.

**Comment by geneidy** [comment]
Hey,

Hope you were able to resolve this. If not, this was discussed on gitter and the interledger forum: https://forum.interledger.org/t/setting-up-moneyd-on-ubuntu-18/597/3

You'll have to configure moneyd with a different btp host that default. 

Delete .moneyd.test.json
run: moneyd xrp:configure --testnet --advanced
When asked for the btp host enter: testnet.ilpnetwork.dev
Press enter for the default options after
once done run: moneyd xrp:start --testnet

Hope this helps.

**Comment by wa1one** [comment]
It works , thanks @geneidy
