### ISSUE TITLE
moneyd, xrp secret

### ISSUE THREAD

**Issue by lacekim** [interledgerjs/moneyd#127]
```
moneyd xrp:configure --admin-api-port 7769
? XRP secret (master or regular key):
```

What do I do?

**Comment by lacekim** [comment]
Moneyd Error
A request made by Moneyd GUI has failed. This can occur if the Admin API is not exposed by Moneyd.

To make sure that your Admin API is reachable, run Moneyd with the --admin-api-port 7769 flag.

```
Stack Trace
FetchError: request to http://localhost:7769/status failed, reason: connect ECONNREFUSED ::1:7769
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/moneyd-gui/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:488:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by lacekim** [comment]
made the account and still having the issue 
```
lacekim @lacekim Nov 21 00:56
https://pasteboard.co/rl1pdHktsk3y.png running into issue

lacekim @lacekim Nov 21 14:39
This is the part im stuck on "(base) ➜ ~ moneyd --testnet xrp:configure
fatal: Error: config already exists for uplinkName=xrp file=/Users/mikecallahan/.moneyd.test.json
at Function.buildConfig (/usr/local/lib/node_modules/moneyd/src/index.js:48:13)
at Object.handler (/usr/local/lib/node_modules/moneyd/bin/moneyd.js:71:14)
at Object.runCommand (/usr/local/lib/node_modules/moneyd/node_modules/yargs/lib/command.js:238:44)
at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/moneyd/node_modules/yargs/yargs.js:1063:30)
at Object.get [as argv] (/usr/local/lib/node_modules/moneyd/node_modules/yargs/yargs.js:1004:21)
at Object.<anonymous> (/usr/local/lib/node_modules/moneyd/bin/moneyd.js:108:3)
at Module._compile (node:internal/modules/cjs/loader:1205:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
at Module.load (node:internal/modules/cjs/loader:1068:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
(base) ➜ ~ moneyd --testnet xrp:start
88
88
88
88,dPYba,,adPYba, ,adPPYba, 8b,dPPYba, ,adPPYba, 8b d8 ,adPPYb,88
88P' "88" "8a a8" "8a 88P' "8a a8P_____888b d8' a8" Y88 88 88 88 8b d8 88 88 8PP"""""""8b d8' 8b 88
88 88 88 "8a, ,a8" 88 88 "8b, ,aa 8b,d8' "8a, ,d88 88 88 88"YbbdP"' 88 88 "Ybbd8"' Y88'"8bbdP"Y8
d8'
d8'
starting moneyd
2022-11-21T19:34:59.425Z connector:route-broadcaster info generated random routing secret.
2022-11-21T19:34:59.442Z connector:accounts info add account. accountId=parent
2022-11-21T19:34:59.445Z connector:accounts info add account. accountId=local
2022-11-21T19:34:59.490Z connector:admin-api info listen called
2022-11-21T19:34:59.493Z connector:balance-middleware info initializing balance for account. accountId=parent minimumBalance=-Infinity maximumBalance=20000000
2022-11-21T19:34:59.494Z connector:balance-middleware info initializing balance for account. accountId=local minimumBalance=-Infinity maximumBalance=Infinity
npm install -g ilp-curl
echo "This is my example file" > example.txt
"

lacekim @lacekim 16:25
https://medium.com/interledger-blog/use-interledger-with-moneyd-gui-21dee0dc8ba0 ok, have 35 xrp in a account. its fully incorporated into moneyd "(base) ➜ ~ moneyd xrp:configure --admin-api-port 7769
? XRP secret (master or regular key): *
? XRP address: rH4o*"
``` however im still coming up with these errors on the GUI, its saying this "--admin-api-port 7769" need a little help guys, sorry

**Comment by Julietnacy** [comment]
@lacekim Has your issue already been escalated?
