### ISSUE TITLE
MoneyD Issue

### ISSUE THREAD

**Issue by fletch71** [interledgerjs/moneyd#44]
ilp-plugin-btp processing btp packet {"type":2,"requestId":3999174485,"data":{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:45:55.552Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}} +11s
  ilp-plugin-btp received BTP packet (TYPE_ERROR, RequestId: 3999174485): {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:45:55.552Z","data":"Cannot read property 'Account' of undefined","protocolData":[]} +0ms
2018-06-17T09:45:55.605Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:45:55.552Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}
    at Plugin.callback (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:343:20)
    at Object.onceWrapper (events.js:273:13)
    at Plugin.emit (events.js:182:13)
    at Plugin._handleIncomingBtpPacket (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:378:14)
    at Plugin._handleIncomingWsMessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:274:18)
    at WebSocketReconnector.EventEmitter.emit (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at WebSocket._instance.on (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/ws-reconnect.js:20:61)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/node_modules/ws/lib/Receiver.js:380:14)

**Comment by joekenj** [comment]
Did you managed to resolve this issue?
