### ISSUE TITLE
Cannot read property 'Account' of undefined

### ISSUE THREAD

**Issue by KoenWellekens** [interledgerjs/moneyd#45]
When I try to run moneyd-xrp i get the followin error:

2018-06-17T09:35:31.329Z ilp-plugin-xrp-asym-client creating outgoing channel
2018-06-17T09:35:31.706Z ilp-plugin-xrp-asym-client signing transaction
2018-06-17T09:35:32.152Z ilp-plugin-xrp-asym-client submitted outgoing channel tx to validator
2018-06-17T09:35:32.152Z ilp-plugin-xrp-asym-client waiting for transaction to be added to the ledger
2018-06-17T09:35:36.189Z ilp-plugin-xrp-asym-client transaction complete
2018-06-17T09:35:36.592Z ilp-plugin-xrp-asym-client no client channel has been established; requesting
2018-06-17T09:35:48.086Z ilp-plugin-btp processing btp packet {"type":2,"requestId":161871734,"data":{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:35:48.032Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}}
2018-06-17T09:35:48.086Z ilp-plugin-btp received BTP packet (TYPE_ERROR, RequestId: 161871734): {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:35:48.032Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}
**2018-06-17T09:35:48.087Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-17T09:35:48.032Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}**
 ```
   at Plugin.callback (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:343:20)
    at Object.onceWrapper (events.js:273:13)
    at Plugin.emit (events.js:182:13)
    at Plugin._handleIncomingBtpPacket (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:378:14)
    at Plugin._handleIncomingWsMessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:274:18)
    at WebSocketReconnector.EventEmitter.emit (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at WebSocket._instance.on (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/ws-reconnect.js:20:61)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/node_modules/ws/lib/Receiver.js:380:14)

```

**Comment by jnieuwenhuijzen** [comment]
I am getting this error too (trying to connect for the 1st time).  Did you manage to solve it?

`starting moneyd
2018-09-23T10:53:28.265Z connector:route-broadcaster info generated random routing secret.
2018-09-23T10:53:28.272Z connector:accounts info add account. accountId=parent
2018-09-23T10:53:28.275Z connector:accounts info add account. accountId=local
2018-09-23T10:53:41.512Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-09-23T10:53:41.492Z","data":"Cannot read property 'Account' of undefined","protocolData":[]}
    at Plugin.callback (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:634:20)
    at Plugin.listener (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous> (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:679:14)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:390:16)
    at Plugin.<anonymous> (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:496:18)`

**Comment by emschwartz** [comment]
Did you run moneyd xrp:configure before running start?

**Comment by christophersanborn** [comment]
I also am receiving this same error on testnet.   Is there any solution yet?

In .moneyd.test.json the server key and xrpServer key are:

```
"server": "btp+wss://ETP4vvLENdNNKdaSJyu6haIc6ziiPMtX3IVFUW3Jjc4:2eb7b97cc8f52148aedcfbe0c21e9d816caead905c9ef9c56e4ac865bc576f43@strata-ilsp.com/testnet/xrp",
"xrpServer": "wss://s.altnet.rippletest.net:51233"
```

**Comment by omrtozd** [comment]
I'm getting the same error, is anyone fixed it?

**Comment by wa1one** [comment]
same error

**Comment by Mike-Huggins** [comment]
Same error. Believe it is to do with the test net but no idea how to resolve!

**Comment by jellicoe** [comment]
same here..."data":"Cannot read property 'Account' of undefined","protocolData":[]}
