### ISSUE TITLE
Insufficient reserve to complete requested operation - moneyd xrp:start

### ISSUE THREAD

**Issue by whaus7** [interledgerjs/moneyd#47]
My account definitely has more than the 35 recommended minimum
https://bithomp.com/explorer/rPyURAVppfVm76jdSRsPyZBACdGiXYu4bf
Getting this error when running moneyd xrp:start

starting moneyd
2018-06-22T13:28:59.385Z connector:route-broadcaster info generated random routing secret.
2018-06-22T13:28:59.392Z connector:accounts info add account. accountId=parent
2018-06-22T13:28:59.395Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-06-22T13:28:59.395Z connector:accounts info add account. accountId=local
2018-06-22T13:28:59.418Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=local
2018-06-22T13:28:59.419Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-06-22T13:28:59.419Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-06-22T13:29:07.694Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-06-22T13:29:07.663Z","data":"tx failed: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete requested operation.\",\"ledger_hash\":\"E26F7527624A507DA85D19E2C5994A9C3700661D803AC1F9F35247DC78F6316D\",\"ledger_index\":39563466,\"meta\":{\"AffectedNodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rK6g2UYc4GpQH8DYdPG7wywyQbxkJpQTTN\",\"Balance\":\"3172117539\",\"Flags\":0,\"OwnerCount\":630,\"Sequence\":194738},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"1779FCFCF53ACAF81150E49FCDA32AE74B3DB67FCA77C054E0DEA3DEC4EFE053\",\"PreviousFields\":{\"Balance\":\"3172117551\",\"Sequence\":194737},\"PreviousTxnID\":\"ED051CA971EED4961C5F3CBC74D6010FEA4A0D780FC86A8A1DFD9336063D8D51\",\"PreviousTxnLgrSeq\":39563449}}],\"TransactionIndex\":36,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transaction\":{\"Account\":\"rK6g2UYc4GpQH8DYdPG7wywyQbxkJpQTTN\",\"Amount\":\"1000000\",\"Destination\":\"rPyURAVppfVm76jdSRsPyZBACdGiXYu4bf\",\"Fee\":\"12\",\"Flags\":2147483648,\"LastLedgerSequence\":39563467,\"PublicKey\":\"ED852D6E57ED4ED73F2403DAA1A668FAD2BF35F6FE04567B960E813EB0C4561AAB\",\"Sequence\":194737,\"SettleDelay\":3600,\"SigningPubKey\":\"03D488B5AA26C87CB14BF23D470520F592A0006A916F5FEEAAB48335D8811A2E9F\",\"SourceTag\":3405230851,\"TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"3045022100FF7B135AE304B92B2EE32154EE9CA06B19BDEC4762C44A091F4FB913F478C93102201C7C16E1C2493BCA95118E2E0CB59AB87CAE4938BCA80B64E59A8B114C531D46\",\"date\":582989342,\"hash\":\"9767BF8D612854E01A922F2428647BD00E085AA055ADF3A57E48AC726A94A4BA\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]}
    at Plugin.callback (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:343:20)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Plugin.emit (events.js:214:7)
    at Plugin._handleIncomingBtpPacket (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:378:14)
    at Plugin._handleIncomingWsMessage (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/index.js:274:18)
    at WebSocketReconnector.EventEmitter.emit (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at WebSocket._instance.on (/usr/local/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/ws-reconnect.js:20:61)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)

Everything seems in order... any ideas?

**Comment by sharafian** [comment]
That's insufficient reserve on the connectors end; I'll fix that and let you know when it's resolved

**Comment by whaus7** [comment]
Awesome!!! Soooo stoke about all these pieces coming together. Lemme know if I can do anything for any of your Codius projects! I'm a frontend/react specialist

I glanced and saw the repository for showing a visual of Codius hosts. Haven't seen what it looks like but that would right up my ally

**Comment by sharafian** [comment]
Thanks! Are you already in our community at https://gitter.im/codius/codius-chat and https://gitter.im/interledger/Lobby ?

This issue should be resolved if you try again; funds have been added to Scylla

**Comment by GaetanoH** [comment]
I'm having the same issue on my machine yesterday.

`Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-23T11:12:32.734Z","data":"tx failed: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete requested operation.\",\"ledger_hash\":\"55EA854DBF7166811BFF151BF62D63D8BE5CE56D224C321B08334B684B72495A\",\"ledger_index\":40280098,\"meta\":{\"AffectedNodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Balance\":\"1020466006\",\"Flags\":0,\"OwnerCount\":200,\"Sequence\":28379},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"D16BF3F23AFB01CA5AC7860F9AF8037117972D5A389DDFDBB5A1064742B154D8\",\"PreviousFields\":{\"Balance\":\"1020466018\",\"Sequence\":28378},\"PreviousTxnID\":\"DC3DBF1E7BB3B26A9C371D3F7375944B888203886C244BBADFBBECBE47441AF5\",\"PreviousTxnLgrSeq\":40280039}}],\"TransactionIndex\":11,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transaction\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Amount\":\"1000000\",\"Destination\":\"rn2z9QoY5FU5tUNPFU9ur9kk6anwUuTqhF\",\"Fee\":\"12\",\"Flags\":2147483648,\"LastLedgerSequence\":40280099,\"PublicKey\":\"ED14895408927960E07A08230906BF89A5751113E217F093BFA44379C8A2B12F74\",\"Sequence\":28378,\"SettleDelay\":3600,\"SigningPubKey\":\"03C5FFF69D648EBDDF19998A668BDEEA6ABAFDA446950ECFEEEB2578AC142B7409\",\"SourceTag\":449365037,\"TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"3045022100968A3FE2D059FA13E80848C77604DB1D9C81FF962F90A84ABF596F89C2AC570402204A57012B3C9085AD7081A276E9F1B1041982A577E3953AA260DC5A968D004F39\",\"date\":585659551,\"hash\":\"7E42DA4771B2B0F5DB191905CB9D9BB896CFF20752A9ECB1DBD6139DEF122927\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]}`
