### ISSUE TITLE
Insufficient reserve to complete requested operation

### ISSUE THREAD

**Issue by m6silver** [interledgerjs/moneyd#69]
Hi, I'm encountering this issue no matter how many time I have to reinstall CentOS and Codius from fresh, used new wallet, change different hardware server and funded 360 XRP into the wallet and still i'm getting Insufficient reserve. Anyone able to help?

starting moneyd
2018-08-20T15:40:47.912Z connector:route-broadcaster info generated random routing secret.
2018-08-20T15:40:47.921Z connector:accounts info add account. accountId=parent
2018-08-20T15:40:47.924Z connector:accounts info add account. accountId=local
2018-08-20T15:40:47.955Z connector:rate-limit-middleware debug created token bucket for account. accountId=parent refillPeriod=60000 refillCount=10000 capacity=10000
2018-08-20T15:40:47.957Z connector:balance-middleware debug initializing balance for account. accountId=parent minimumBalance=-Infinity maximumBalance=20000
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace registering data handler +0ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace registering money handler +1ms
2018-08-20T15:40:47.958Z connector:rate-limit-middleware debug created token bucket for account. accountId=local refillPeriod=60000 refillCount=10000 capacity=10000
2018-08-20T15:40:47.958Z connector:balance-middleware debug initializing balance for account. accountId=local minimumBalance=-Infinity maximumBalance=Infinity
2018-08-20T15:40:47.959Z connector:accounts debug connecting to parent. accountId=parent
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace connected to server +838ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace processing btp packet {"type":1,"requestId":3449494270,"data":{"protocolData":[]}} +199ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace received BTP packet (TYPE_RESPONSE, RequestId: 3449494270): {"protocolData":[]} +0ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace processing btp packet {"type":1,"requestId":612453047,"data":{"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,97,100,100,114,101,115,115,34,58,34,114,74,78,97,55,49,99,76,67,106,122,81,71,54,56,111,78,106,104,52,102,67,85,113,67,90,83,71,78,107,87,68,114,77,34,44,34,97,99,99,111,117,110,116,34,58,34,103,46,97,102,114,105,99,97,46,111,112,101,110,46,98,68,75,68,54,51,77,111,116,86,103,112,49,119,66,72,84,107,74,74,74,116,77,45,56,118,117,116,88,121,118,86,99,71,49,45,95,121,99,72,104,73,65,34,44,34,99,117,114,114,101,110,99,121,83,99,97,108,101,34,58,54,44,34,99,104,97,110,110,101,108,34,58,34,56,55,52,48,67,68,57,54,48,66,48,67,56,53,49,67,53,52,48,54,54,56,53,69,68,68,53,56,50,56,54,65,55,67,57,65,54,56,49,66,55,54,53,49,68,52,49,54,66,50,70,66,56,50,65,48,53,52,65,53,69,55,53,53,34,125]}}]}} +197ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace received BTP packet (TYPE_RESPONSE, RequestId: 612453047): {"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,97,100,100,114,101,115,115,34,58,34,114,74,78,97,55,49,99,76,67,106,122,81,71,54,56,111,78,106,104,52,102,67,85,113,67,90,83,71,78,107,87,68,114,77,34,44,34,97,99,99,111,117,110,116,34,58,34,103,46,97,102,114,105,99,97,46,111,112,101,110,46,98,68,75,68,54,51,77,111,116,86,103,112,49,119,66,72,84,107,74,74,74,116,77,45,56,118,117,116,88,121,118,86,99,71,49,45,95,121,99,72,104,73,65,34,44,34,99,117,114,114,101,110,99,121,83,99,97,108,101,34,58,54,44,34,99,104,97,110,110,101,108,34,58,34,56,55,52,48,67,68,57,54,48,66,48,67,56,53,49,67,53,52,48,54,54,56,53,69,68,68,53,56,50,56,54,65,55,67,57,65,54,56,49,66,55,54,53,49,68,52,49,54,66,50,70,66,56,50,65,48,53,52,65,53,69,55,53,53,34,125]}}]} +0ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace got info: { address: 'rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM',
  account: 'g.africa.open.bDKD63MotVgp1wBHTkJJJtM-8vutXyvVcG1-_ycHhIA',
  currencyScale: 6,
  channel:
   '8740CD960B0C851C5406685EDD58286A7C9A681B7651D416B2FB82A054A5E755' } +0ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace no client channel has been established; requesting +3s
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace processing btp packet {"type":2,"requestId":1425364959,"data":{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-08-20T15:40:59.546Z","data":"tx failed: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete requested operation.\",\"ledger_hash\":\"1AC40145B5CB5734EC099CA8DD843F2EB4732C7D646E20F33E2DC24AC7B89743\",\"ledger_index\":40936929,\"meta\":{\"AffectedNodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Balance\":\"1446966723\",\"Flags\":0,\"OwnerCount\":285,\"Sequence\":32185},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"D16BF3F23AFB01CA5AC7860F9AF8037117972D5A389DDFDBB5A1064742B154D8\",\"PreviousFields\":{\"Balance\":\"1446966735\",\"Sequence\":32184},\"PreviousTxnID\":\"83568A495D1E01E940ABFA59BECFC8C9CAC9CD896805EE0C750A2AABADCE18FE\",\"PreviousTxnLgrSeq\":40936928}}],\"TransactionIndex\":24,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transaction\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Amount\":\"1000000\",\"Destination\":\"rJmfhJk6oGj976Jcke5fmWqMDtHxD33znW\",\"Fee\":\"12\",\"Flags\":2147483648,\"LastLedgerSequence\":40936930,\"PublicKey\":\"EDFA466412BAEDEAA8EB0539AD9A83D40331189E3A3F829E550AE024760EE86260\",\"Sequence\":32184,\"SettleDelay\":3600,\"SigningPubKey\":\"03C5FFF69D648EBDDF19998A668BDEEA6ABAFDA446950ECFEEEB2578AC142B7409\",\"SourceTag\":3286349623,\"TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"30450221008F9DE15C2E06A9829E2D80204806ABF1FD946660B8A8D6BD8BE9D6B36C2F59D102206780C047D46475F596BECD25F12337418B97CAF99FF3D98D9D8310CCF193218B\",\"date\":588094860,\"hash\":\"18A694E051E07BD2ED5AEF59CFA8DBC3BEBF9DE86710F44ACFE956FFBF6FC786\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]}} +7s
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace received BTP packet (TYPE_ERROR, RequestId: 1425364959): {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-08-20T15:40:59.546Z","data":"tx failed: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete requested operation.\",\"ledger_hash\":\"1AC40145B5CB5734EC099CA8DD843F2EB4732C7D646E20F33E2DC24AC7B89743\",\"ledger_index\":40936929,\"meta\":{\"AffectedNodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Balance\":\"1446966723\",\"Flags\":0,\"OwnerCount\":285,\"Sequence\":32185},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"D16BF3F23AFB01CA5AC7860F9AF8037117972D5A389DDFDBB5A1064742B154D8\",\"PreviousFields\":{\"Balance\":\"1446966735\",\"Sequence\":32184},\"PreviousTxnID\":\"83568A495D1E01E940ABFA59BECFC8C9CAC9CD896805EE0C750A2AABADCE18FE\",\"PreviousTxnLgrSeq\":40936928}}],\"TransactionIndex\":24,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transaction\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Amount\":\"1000000\",\"Destination\":\"rJmfhJk6oGj976Jcke5fmWqMDtHxD33znW\",\"Fee\":\"12\",\"Flags\":2147483648,\"LastLedgerSequence\":40936930,\"PublicKey\":\"EDFA466412BAEDEAA8EB0539AD9A83D40331189E3A3F829E550AE024760EE86260\",\"Sequence\":32184,\"SettleDelay\":3600,\"SigningPubKey\":\"03C5FFF69D648EBDDF19998A668BDEEA6ABAFDA446950ECFEEEB2578AC142B7409\",\"SourceTag\":3286349623,\"TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"30450221008F9DE15C2E06A9829E2D80204806ABF1FD946660B8A8D6BD8BE9D6B36C2F59D102206780C047D46475F596BECD25F12337418B97CAF99FF3D98D9D8310CCF193218B\",\"date\":588094860,\"hash\":\"18A694E051E07BD2ED5AEF59CFA8DBC3BEBF9DE86710F44ACFE956FFBF6FC786\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]} +1ms
2018-08-20T15:40:59.654Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-08-20T15:40:59.546Z","data":"tx failed: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete requested operation.\",\"ledger_hash\":\"1AC40145B5CB5734EC099CA8DD843F2EB4732C7D646E20F33E2DC24AC7B89743\",\"ledger_index\":40936929,\"meta\":{\"AffectedNodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Balance\":\"1446966723\",\"Flags\":0,\"OwnerCount\":285,\"Sequence\":32185},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"D16BF3F23AFB01CA5AC7860F9AF8037117972D5A389DDFDBB5A1064742B154D8\",\"PreviousFields\":{\"Balance\":\"1446966735\",\"Sequence\":32184},\"PreviousTxnID\":\"83568A495D1E01E940ABFA59BECFC8C9CAC9CD896805EE0C750A2AABADCE18FE\",\"PreviousTxnLgrSeq\":40936928}}],\"TransactionIndex\":24,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transaction\":{\"Account\":\"rJNa71cLCjzQG68oNjh4fCUqCZSGNkWDrM\",\"Amount\":\"1000000\",\"Destination\":\"rJmfhJk6oGj976Jcke5fmWqMDtHxD33znW\",\"Fee\":\"12\",\"Flags\":2147483648,\"LastLedgerSequence\":40936930,\"PublicKey\":\"EDFA466412BAEDEAA8EB0539AD9A83D40331189E3A3F829E550AE024760EE86260\",\"Sequence\":32184,\"SettleDelay\":3600,\"SigningPubKey\":\"03C5FFF69D648EBDDF19998A668BDEEA6ABAFDA446950ECFEEEB2578AC142B7409\",\"SourceTag\":3286349623,\"TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"30450221008F9DE15C2E06A9829E2D80204806ABF1FD946660B8A8D6BD8BE9D6B36C2F59D102206780C047D46475F596BECD25F12337418B97CAF99FF3D98D9D8310CCF193218B\",\"date\":588094860,\"hash\":\"18A694E051E07BD2ED5AEF59CFA8DBC3BEBF9DE86710F44ACFE956FFBF6FC786\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]}
    at Plugin.callback (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:441:20)
    at Plugin.listener (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous> (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:476:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:340:16)
    at Plugin.<anonymous> (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:329:18)
  ilp-xrp-channel-watcher checking 0 channels for expiry +0ms
  ilp-ws-reconnect:debug websocket disconnected with 1006; reconnect in 5000 +0ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace connected to server +1m
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace processing btp packet {"type":1,"requestId":899175628,"data":{"protocolData":[]}} +212ms
  connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace received BTP packet (TYPE_RESPONSE, RequestId: 899175628): {"protocolData":[]} +0ms

**Comment by m6silver** [comment]
Issue resolved. Due to bad BTP host of parent connector having not enough reserve.
