### ISSUE TITLE
"Insufficient reserve to complete request ed operation"

### ISSUE THREAD

**Issue by fjx2000** [interledgerjs/moneyd#70]
## I have available: 315.973586 XRP in my account, but I failed to run "moneyd xrp:start" with "Insufficient reserve to complete request ed operation".  Any idea about this issue ?

2018-08-21T22:39:28.565Z connector:route-broadcaster info generated random routing secret.
2018-08-21T22:39:28.572Z connector:accounts info add account. accountId=parent
2018-08-21T22:39:28.575Z connector:accounts info add account. accountId=local
2018-08-21T22:39:38.046Z connector:app error Error: {"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-08-21T22:39:37.889Z","data":"tx fai led: {\"engine_result\":\"tecINSUFFICIENT_RESERVE\",\"engine_result_code\":141,\"engine_result_message\":\"Insufficient reserve to complete request ed operation.\",\"ledger_hash\":\"4C48D0160746C6985F4249541397B99F8783C5E5C791868D1FA1D5C475E8C6D7\",\"ledger_index\":40966621,\"meta\":{\"Affected Nodes\":[{\"ModifiedNode\":{\"FinalFields\":{\"Account\":\"rhAG7gdd2CKAeaEQCwz5pkN9o1KK6CPNGn\",\"Balance\":\"831847639\",\"Flags\":0,\"OwnerCount\ ":162,\"Sequence\":4064},\"LedgerEntryType\":\"AccountRoot\",\"LedgerIndex\":\"2A0FA6C99CB992D9874E3186E03FC73ABE73E893843EE0E50B00E0F7F43CBAD0\",\ "PreviousFields\":{\"Balance\":\"831847651\",\"Sequence\":4063},\"PreviousTxnID\":\"BE0EC1B26B0DCA9AD32174FAAEED1B14497CB8D2F599390DE181319101DAB69 2\",\"PreviousTxnLgrSeq\":40966598}}],\"TransactionIndex\":26,\"TransactionResult\":\"tecINSUFFICIENT_RESERVE\"},\"status\":\"closed\",\"transactio n\":{\"Account\":\"rhAG7gdd2CKAeaEQCwz5pkN9o1KK6CPNGn\",\"Amount\":\"1000000\",\"Destination\":\"r9WxHH67JH8zGu5jZG2edfP5KpMiD98PGJ\",\"Fee\":\"12\ ",\"Flags\":2147483648,\"LastLedgerSequence\":40966622,\"PublicKey\":\"EDBBAADDC5A9F2E869E0FE717DE33A63A40B8262734EA32C93D2DD2B8EFD50A3E9\",\"Seque nce\":4063,\"SettleDelay\":3600,\"SigningPubKey\":\"0318E42680BC1AEB740DBC00B94EB668A21D658C532B5DD1B57658AF56179FE827\",\"SourceTag\":1029551716,\ "TransactionType\":\"PaymentChannelCreate\",\"TxnSignature\":\"3044022009D988FBB8B84B0237739D09B9D7FBFA0E8D1ABEFCBCD1A6237F61AD78812268022046A88F7F C562BA806676B8B3DDD6F56E983C0BD77393F60DE8B4D87C14BB20B1\",\"date\":588206372,\"hash\":\"1CFBF5846E277EBA59A02A15B660601FE1DE1C847279E77BA7F9B8F338 2D8F78\"},\"type\":\"transaction\",\"validated\":true}","protocolData":[]}
    at Plugin.callback (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:441:20)
    at Plugin.listener (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290 :17)
    at Plugin.EventEmitter.emit (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitte r2.js:357:19)
    at Plugin.<anonymous> (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:476:14)
    at Generator.next (<anonymous>)
    at /home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/ind ex.js:340:16)
    at Plugin.<anonymous> (/home/alex/.nvm/versions/node/v9.1.0/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:329:18)
^C
alex@codius1:~$
alex@codius1:~$
alex@codius1:~$ moneyd xrp:info
fetching channels...
connecting to xrp ledger...
account: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
balance: 355.973586 XRP
  reserved: 40 XRP
  available: 315.973586 XRP

**Comment by sharafian** [comment]
The connector on the other side must be out of XRP reserve. Can you find the `server` field in your `~/.moneyd.json` so that the host can be notified?

**Comment by fjx2000** [comment]
"server": "btp+wss://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@btp.connector0.com",
