### ISSUE TITLE
How to close Payment Channel after rebuilding server?

### ISSUE THREAD

**Issue by g10chy** [interledgerjs/moneyd#74]
Hi,
I have had to rebuild my server from scratch. In the process, I am now unable to close the Payment Channel to reclaim my 10 XRP.

Please can you help with the required steps?

Thanks,
Chris

**Comment by g10chy** [comment]
I have managed to put together a new .moneyd.json file and now able to see the channel with "moneyd xrp:info".
However, I get this error when trying to run cleanup:

`fatal: { AssertionError [ERR_ASSERTION]: parameter store must be object
    at new TransactionFactory (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/transaction-factory.js:8:5)
    at new TxSubmitter (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/tx-submitter.js:36:23)
    at module.exports (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/tx-submitter.js:213:22)
    at XrpUplink._submitter (/usr/lib/node_modules/moneyd-uplink-xrp/index.js:235:12)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }`

**Comment by adamstraube** [comment]
Hi @g10chy, I have the same issue also. This is also an issue in the moneyd-uplink-xrp repo here: https://github.com/interledgerjs/moneyd-uplink-xrp/issues/28
